name: Run xcrun

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-13, macos-14]
      fail-fast: false

    steps:
    - run: sudo xcode-select -s /Library/Developer/CommandLineTools  
    - run: xcrun --show-sdk-version
